ORIENTATION_MESSAGE_NAME = 'ATTITUDE'
POWER_STATUS = 'POWER_STATUS'
GLOBAL_POSITION_INT = 'GLOBAL_POSITION_INT'
GPS_RAW_INT = 'GPS_RAW_INT'
GPS_RAW = 'GPS_RAW'
GPS_NO_FIX = 1
GPS_2D_FIX = 2
GPS_3D_FIX = 3